# Generated by Django 4.1.2 on 2022-10-16 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 16, 8, 49, 36, 199723, tzinfo=datetime.timezone.utc), verbose_name='birthday'),
            preserve_default=False,
        ),
    ]
