# Generated by Django 4.1.2 on 2022-10-16 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('users', '0005_alter_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name='body')),
                ('seen', models.BooleanField(default=False)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reply', to='users.notification')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_post', to='post.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reply', to='users.bookmark')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_post', to='post.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
