# Generated by Django 4.1.2 on 2022-10-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow_follower_follow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
