# Generated by Django 4.1.2 on 2022-10-27 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
