# Generated by Django 4.1.2 on 2022-12-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
