# Generated by Django 4.1.2 on 2022-10-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='reply',
            new_name='tweet',
        ),
    ]
