# Generated by Django 4.1.2 on 2022-10-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_reply_tweet_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='reply',
        ),
    ]
