# Generated by Django 4.1.2 on 2022-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_retweet_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='quote',
            field=models.TextField(null=True, verbose_name='quote'),
        ),
    ]
