# Generated by Django 4.1.2 on 2022-10-27 09:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_retweet_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retweet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='quote',
        ),
        migrations.AddField(
            model_name='retweet',
            name='content',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='retweet',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retweet',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='media files'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_reply',
            field=models.BooleanField(default=False, editable=False, verbose_name='is reply'),
        ),
    ]
