# Generated by Django 4.1.2 on 2022-10-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_retweet_options_alter_tweet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='reply',
            new_name='reply_to',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tweet', to='post.tweet'),
        ),
    ]
