# Generated by Django 4.1.2 on 2022-10-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_delete_retweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_reply',
        ),
    ]
