# Generated by Django 4.1.2 on 2022-10-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_tweet_is_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='post.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet', to='post.tweet'),
        ),
    ]
