# Generated by Django 4.1.2 on 2022-10-30 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='hash tags or usernames'), default=list, size=None),
        ),
    ]
