# Generated by Django 4.1.2 on 2022-10-30 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0015_remove_tweet_likes_alter_tweet_content_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', through='post.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
