# Generated by Django 4.1.2 on 2022-10-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_tweet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='post.tweet'),
        ),
    ]
