# Generated by Django 4.1.2 on 2022-11-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_tweet_reply_to_alter_tweet_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='retweet',
        ),
    ]
