# Generated by Django 4.1.2 on 2022-11-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_rename_tweet_tweet_retweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='reply_to',
            new_name='reply',
        ),
    ]
