# Generated by Django 4.1.2 on 2023-02-10 18:20

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_rename_reply_to_tweet_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(editable=False, unique=True, upload_to=post.models.tweet_media_filename, verbose_name='tweet media file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='post.tweet')),
            ],
        ),
    ]
