# Generated by Django 4.1.2 on 2022-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Group Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='is group'),
        ),
    ]
