# Generated by Django 4.1.2 on 2023-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time', '0004_group_description_group_is_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tweet',
        ),
        migrations.AddField(
            model_name='notification',
            name='model',
            field=models.CharField(default='Tweet', max_length=255, verbose_name='model Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='model_id',
            field=models.URLField(default='02bb2d70-d8a7-45a6-8880-220c50b8ceff', verbose_name='model id'),
            preserve_default=False,
        ),
    ]
