# Generated by Django 4.1.2 on 2023-01-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time', '0006_alter_notification_model_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='id',
        ),
        migrations.AlterField(
            model_name='clients',
            name='channel_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
